# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vwwo-pPijEmQdtljE7Ise4CZo0J5kqkY
"""

import streamlit as st
import pandas as pd
import plotly.express as px
from supabase import create_client, Client
from datetime import datetime

# Page config
st.set_page_config(
    page_title="African Economic Indicators",
    page_icon="🌍",
    layout="wide"
)

# Custom CSS
st.markdown("""
<style>
    .main { background-color: #080c14; color: white; }
    .stMetric {
        background-color: #0d1420;
        border: 1px solid rgba(0,212,255,0.15);
        border-radius: 10px;
        padding: 10px;
    }
</style>
""", unsafe_allow_html=True)

# Supabase connection
@st.cache_resource
def init_supabase():
    SUPABASE_URL = st.secrets["https://lglcfjjqdqtthjbrkuei.supabase.co"]
    SUPABASE_KEY = st.secrets["sb_secret_J41IuV2ScauA8AExyZetkA_ZFgVjxxt"]
    return create_client(SUPABASE_URL, SUPABASE_KEY)
@st.cache_data(ttl=3600)
def load_data():
    supabase = init_supabase()
    response = supabase.table('economic_indicators').select("*").execute()
    df = pd.DataFrame(response.data)
    df['date'] = pd.to_datetime(df['date'])
    df['year'] = df['date'].dt.year
    return df

# Load data
df = load_data()

# Header
st.title(" African Economic Indicators Dashboard")
st.markdown("**Live data pipeline pulling from World Bank API → Supabase → This dashboard**")
st.markdown(f"*Last updated: {datetime.now().strftime('%B %d, %Y')}*")
st.markdown("---")

# Sidebar filters
st.sidebar.title(" Filters")
selected_countries = st.sidebar.multiselect(
    "Countries",
    options=df['country'].unique(),
    default=df['country'].unique()
)

selected_years = st.sidebar.multiselect(
    "Years",
    options=sorted(df['year'].unique(), reverse=True),
    default=sorted(df['year'].unique(), reverse=True)
)

# Filter
filtered = df[
    (df['country'].isin(selected_countries)) &
    (df['year'].isin(selected_years))
]

# KPI Cards
st.subheader(" Latest Key Metrics")
col1, col2, col3, col4, col5 = st.columns(5)

latest = filtered[filtered['year'] == filtered['year'].max()]

for i, country in enumerate(['Nigeria', 'South Africa', 'Kenya', 'Ghana', 'Ethiopia']):
    gdp_val = latest[(latest['country'] == country) &
                     (latest['indicator'] == 'GDP (Billion USD)')]['value']
    val = f"${gdp_val.values[0]:.1f}B" if len(gdp_val) > 0 else "N/A"
    [col1, col2, col3, col4, col5][i].metric(f" {country} GDP", val)

st.markdown("---")

# Row 1 — GDP and Inflation
col1, col2 = st.columns(2)

with col1:
    gdp = filtered[filtered['indicator'] == 'GDP (Billion USD)']
    fig1 = px.bar(gdp, x='country', y='value', color='year',
                  title=' GDP by Country (Billion USD)',
                  barmode='group',
                  color_discrete_sequence=px.colors.qualitative.Bold)
    fig1.update_layout(
        plot_bgcolor='#0d1420', paper_bgcolor='#0d1420',
        font_color='white', title_font_size=14
    )
    st.plotly_chart(fig1, use_container_width=True)

with col2:
    inflation = filtered[filtered['indicator'] == 'Inflation Rate (%)']
    fig2 = px.line(inflation, x='date', y='value', color='country',
                   title=' Inflation Rate Trends (%)',
                   markers=True)
    fig2.update_layout(
        plot_bgcolor='#0d1420', paper_bgcolor='#0d1420',
        font_color='white', title_font_size=14
    )
    st.plotly_chart(fig2, use_container_width=True)

# Row 2 — Unemployment and Trade
col1, col2 = st.columns(2)

with col1:
    unemployment = filtered[filtered['indicator'] == 'Unemployment Rate (%)']
    fig3 = px.bar(unemployment, x='country', y='value', color='country',
                  title='👥 Unemployment Rate (%)',
                  color_discrete_sequence=px.colors.qualitative.Set2)
    fig3.update_layout(
        plot_bgcolor='#0d1420', paper_bgcolor='#0d1420',
        font_color='white', title_font_size=14,
        showlegend=False
    )
    st.plotly_chart(fig3, use_container_width=True)

with col2:
    exports = filtered[filtered['indicator'] == 'Exports % of GDP']
    imports = filtered[filtered['indicator'] == 'Imports % of GDP']
    latest_exp = exports[exports['year'] == exports['year'].max()]
    latest_imp = imports[imports['year'] == imports['year'].max()]

    fig4 = px.bar(
        pd.concat([
            latest_exp.assign(type='Exports'),
            latest_imp.assign(type='Imports')
        ]),
        x='country', y='value', color='type',
        title=' Exports vs Imports % of GDP',
        barmode='group',
        color_discrete_map={'Exports': '#00d4ff', 'Imports': '#ff6b6b'}
    )
    fig4.update_layout(
        plot_bgcolor='#0d1420', paper_bgcolor='#0d1420',
        font_color='white', title_font_size=14
    )
    st.plotly_chart(fig4, use_container_width=True)

# Row 3 — Full indicator comparison
st.subheader(" Full Data Explorer")
pivot = filtered.groupby(['country', 'indicator', 'year'])['value'].mean().reset_index()
pivot = pivot.sort_values(['indicator', 'year'], ascending=[True, False])

fig5 = px.sunburst(
    filtered[filtered['year'] == filtered['year'].max()],
    path=['indicator', 'country'],
    values='value',
    title=' Economic Indicators Breakdown (Latest Year)',
    color='value',
    color_continuous_scale='Blues'
)
fig5.update_layout(
    paper_bgcolor='#0d1420',
    font_color='white',
    title_font_size=14
)
st.plotly_chart(fig5, use_container_width=True)

# Raw data table
st.subheader(" Raw Data")
st.dataframe(
    filtered[['country', 'indicator', 'value', 'year', 'source']]
    .sort_values(['country', 'indicator', 'year'], ascending=[True, True, False]),
    use_container_width=True,
    height=300
)

st.markdown("---")
st.markdown("**Built by Oluwatosin Ajisefinni** | Data Engineer & Analyst | Lagos, Nigeria | [GitHub](https://github.com/Thuqsin) | [LinkedIn](https://linkedin.com/in/oluwatosinajisefinni)")
